openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mint-user/dask/1.0.0
  - description: Dev env
    url: http://127.0.0.1:5000
info:
  version: "1.0.0"
  title: Dask
  description: >-
    TODO application
paths:
  /auth:
    post:
      summary: sign in
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:          # <!--- form field name
                  type: string
                password:    # <!--- form field name
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: OK
    get:
      summary: This is login
      description: >-
        This is login
        Yes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:          # <!--- form field name
                  type: string
                password:    # <!--- form field name
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
           $ref: '#/components/responses/Unauthorized'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
components:
  responses:
   Unauthorized:
    description: Unauthorized
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        password:
          type: string
        token:
          type: string
        token_expires:
          type: string
          format: datetime
          example: "2020-01-23 12:34:56"
      example:
        id: 1
        email: qwe@efd.ru
        token: frf34t34tret43t
        token_expires: "2020-01-23 12:34:56"
      description: users